[package]
name = "portfolio"
version = "0.1.0"
authors = ["Ricardo Murillo <rcjmurillo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
private_ops = []

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0"
binance = { git = "https://github.com/wisespace-io/binance-rs.git" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.6"
chrono = "0.4"
hmac = "0.11.0"
sha2 = "0.9.5"
hex = "0.4"
cli-table = "0.4"
futures = "0.3.15"
async-trait = "0.1.50"
async-stream = "0.3.2"
bytes = "1.0.1"
structopt = "0.3.22"
toml = "0.5.8"