[package]
name = "api-client"
version = "0.1.0"
authors = ["Ricardo Murillo <rcjmurillo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.1"
tokio = { version = "1", features = ["sync", "macros", "test-util"] }
reqwest = { version = "0.11", features = ["json"] }