[package]
name = "exchange"
version = "0.1.0"
authors = ["Ricardo Murillo <rcjmurillo@gmail.com>"]
edition = "2021"

[dependencies]

anyhow = "1.0.44"
async-trait = "0.1.50"
bytes = "1.0.1"
chrono = "0.4"
hmac = "0.11.0"
hex = "0.4"
futures = "0.3.15"
sha2 = "0.9.5"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
quickcheck = "1.0.3"