[package]
name = "portfolio"
version = "0.1.0"
authors = ["Ricardo Murillo <rcjmurillo@gmail.com>"]
edition = "2021"

[dependencies]
binance = { path = "../exchanges/binance" }
coinbase = { path = "../exchanges/coinbase" }
exchange = { path = "../exchanges/exchange" }
operations = { path = "../operations" }

anyhow = "1.0.44"
tokio = { version = "1.17", features = ["full"] }
chrono = "0.4"
cli-table = "0.4"
futures = "0.3.15"
async-trait = "0.1.50"
bytes = "1.0.1"
structopt = "0.3.22"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0"
toml = "0.5.8"
log = "0.4.14"
env_logger = "0.9.0"
tracing = "0.1.31"
tracing-subscriber = "0.3.9"

[dev-dependencies]
quickcheck = "1.0.3"